import Head from "next/head";
import { SignInPage, Navbar } from "components";

const SignIn = () => {
  return (
    <div>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-screen">
        <SignInPage />
      </div>
    </div>
  );
};

export default SignIn;
