import Head from "next/head";
import { HomePage, Navbar, Footer } from "components";

const Home = () => {
  return (
    <div>
      <Head>
        <title>3D EWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-full">
        <HomePage />
      </div>
      <div>
        <Footer />
      </div>
    </div>
  );
};

export default Home;
