import Head from "next/head";
import { HomePage, Navbar } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>3D EWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-screen">
        <HomePage />
      </div>
    </div>
  );
}
