import Head from "next/head";
import { ModalSection, Navbar } from "components";

const ModalsId = () => {
  return (
    <div>
      <Head>
        <title>Modals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-fit relative top-36">
        <ModalSection />
      </div>
    </div>
  );
};

export default ModalsId;
