import Head from "next/head";
import { ModalPage, Navbar } from "components";

const Modals = () => {
  return (
    <div>
      <Head>
        <title>Modals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-screen">
        <ModalPage />
      </div>
    </div>
  );
};

export default Modals;
