import Head from "next/head";
import { PaymentPage, Navbar } from "components";

const Payment = () => {
  return (
    <div>
      <Head>
        <title>Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div className="w-full h-screen">
        <PaymentPage />
      </div>
    </div>
  );
};

export default Payment;
